Clean blazor pages
JacobMoller/BDSAProject pull request #168
Opened 2021-11-19 12:22 UTC by frederikmnielsen

Removed some components and pages we don't need

2021-11-21 12:45 UTC, frejabv requested changes
Looks very nice! But I'm confused about why some of the files are there.

2021-11-21 12:45 UTC, frejabv commented on .local/connection_string.txt
> +Server=localhost;Database=ProjectBank;User Id=sa;Password=P@55w0rd
This should probably be removed

2021-11-21 12:45 UTC, frejabv commented on .local/db_password.txt
> +P@55w0rd
This as well, we might need to look into the gitignore again?

2021-11-21 12:45 UTC, frejabv commented on ProjectBank/Server/Model/Extensions.cs
> +}
Was this not supposed to have been deleted?

2021-11-24 12:45 UTC, JacobMoller approved these changes

2021-11-24 12:51 UTC, frejabv approved these changes

2021-11-24 12:52 UTC, merged